<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>PadelSuper8</RootNamespace>
    <AssemblyName>PadelSuper8</AssemblyName>
  </PropertyGroup>

  <!-- Em Debug no Google Drive, desabilita geração do apphost intermediário para evitar file locks -->
  <PropertyGroup Condition="'$(Configuration)' != 'Release'">
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <!-- Configurações para Executável Portátil Independente (Release / Publish) -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
  </ItemGroup>

</Project>
